<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Clienti_model extends CI_Model
{
    private $primary_key='id_client';
    private $table_name='clienti';

    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get clienti by id
     */
    function get_clienti($id)
    {
        return $this->db->get_where('clienti',array('id_client'=>$id))->row_array();
    }

    /*
    * Get all clienti
    */
    function get_all_clienti($limit=5, $offset=0, $order_column='', $order_type='asc')
    {
//        return $this->db->get('proiecte')->result_array();

        if(empty($order_column)||empty($order_type)){
            $this->db->order_by($this->primary_key,'asc');
        }else {
            $this->db->order_by($order_column,$order_type);
            return $this->db->get($this->table_name, $limit, $offset);
        }

    }

    /*
     * Count all
     */
    function count_all(){
        return $this->db->count_all($this->table_name);
    }

    /*
     * function to add new clienti
     */
    function add_clienti($params)
    {
        $this->db->insert('clienti',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update clienti
     */
    function update_clienti($id,$params)
    {
        $this->db->where('id_client',$id);
        $response = $this->db->update('clienti',$params);
        if($response)
        {
            return "clienti updated successfully";
        }
        else
        {
            return "Error occuring while updating clienti";
        }
    }

    /*
     * function to delete clienti
     */
    function delete_clienti($id)
    {
        $response = $this->db->delete('clienti',array('id'=>$id));
        if($response)
        {
            return "clienti deleted successfully";
        }
        else
        {
            return "Error occuring while deleting clienti";
        }
    }
}
