<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Form_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get form by form_id
     */
    function get_form($form_id)
    {
        return $this->db->get_where('forms',array('form_id'=>$form_id))->row_array();
    }

    /*
     * Get form by project id
     */
    function get_project_form($project_id)
    {
        return $this->db->get_where('forms',array('form_project'=>$project_id))->row_array();
    }


    /*
     * Get all forms
     */
    function get_all_forms()
    {
        return $this->db->get('forms')->result_array();
    }

    /*
     * function to add new form
     */
    function add_form($params, $q, $a, $qId, $qType)
    {

        $this->db->insert('forms',$params);
        $formId = $this->db->insert_id();

        $questionsCount = count($qId);
        //Insert data in tables
        foreach ($q as $qkey => $qItem){
            $this->db->insert('questions', array(
                'question_label' => $qItem,
                'question_form' => $formId,
                'question_type' => $qType[$qkey]
            ));
//        var_dump($qkey);
            $questId = $this->db->insert_id();

            for($i=0; $i<$questionsCount; $i++){
                if ($qId[$i]==$qkey){
                    $this->db->insert('answers', array(
                        'ans_question' => $questId,
                        'ans_value' => $a[$i]
                    ));
                }
            }
        }
    }

    /*
     * function to update form
     */
    function update_form($form_id,$params)
    {
        $this->db->where('form_id',$form_id);
        $response = $this->db->update('forms',$params);
        if($response)
        {
            return "form updated successfully";
        }
        else
        {
            return "Error occuring while updating form";
        }
    }

    /*
     * function to delete form
     */
    function delete_form($form_id)
    {
        $response = $this->db->delete('forms',array('form_id'=>$form_id));
        if($response)
        {
            return "form deleted successfully";
        }
        else
        {
            return "Error occuring while deleting form";
        }
    }
}
