<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Proiecte_model extends CI_Model
{

    private $primary_key='id_proiect';
    private $table_name='proiecte';

    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get proiecte by id
     */
    function get_proiecte($id)
    {
        return $this->db->get_where('proiecte',array('id_proiect'=>$id))->row_array();
    }

    /*
     * Get all proiecte
     */
    function get_all_proiecte($limit=5, $offset=0, $order_column='', $order_type='asc')
    {
//        return $this->db->get('proiecte')->result_array();

        if(empty($order_column)||empty($order_type)){
            $this->db->order_by($this->primary_key,'asc');
        }else {
            $this->db->order_by($order_column,$order_type);
            return $this->db->get($this->table_name, $limit, $offset);
        }

    }

    /*
     * Count all
     */
    function count_all(){
        return $this->db->count_all($this->table_name);
    }

    /*
     * function to add new proiecte
     */
    function add_proiecte($params, $usersProiecte)
    {
        $this->db->insert('proiecte',$params);

        $insert_id = $this->db->insert_id();

        foreach ( $usersProiecte as $item ){
            $this->db->insert('users_proiecte', array(
                'id_user' => $item,
                'id_proiect' => $insert_id
            ));
        }

        return $insert_id;
    }

    /*
     * function to update proiecte
     */
    function update_proiecte($id,$params)
    {
        $this->db->where('id_proiect',$id);
        $response = $this->db->update('proiecte',$params);
        if($response)
        {
            return "proiecte updated successfully";
        }
        else
        {
            return "Error occuring while updating proiecte";
        }
    }

    /*
     * function to delete proiecte
     */
    function delete_proiecte($id)
    {
        $response = $this->db->delete('proiecte',array('id_proiect'=>$id));
        if($response)
        {
            return "proiecte deleted successfully";
        }
        else
        {
            return "Error occuring while deleting proiecte";
        }
    }

    /*
     * Get the client of project.
     */
    function getClient(){
        $this->db->select('*');
        $this->db->from('clienti');
        $this->db->join('proiecte', 'proiecte.client = clienti.id_client');
        $query = $this->db->get();

        return $query;
    }
}
