<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Proiecte_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get proiecte by id
     */
    function get_proiecte($id)
    {
        return $this->db->get_where('proiecte',array('id'=>$id))->row_array();
    }

    /*
     * Get all proiecte
     */
    function get_all_proiecte()
    {
        return $this->db->get('proiecte')->result_array();
    }

    /*
     * function to add new proiecte
     */
    function add_proiecte($params)
    {
        $this->db->insert('proiecte',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update proiecte
     */
    function update_proiecte($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('proiecte',$params);
        if($response)
        {
            return "proiecte updated successfully";
        }
        else
        {
            return "Error occuring while updating proiecte";
        }
    }

    /*
     * function to delete proiecte
     */
    function delete_proiecte($id)
    {
        $response = $this->db->delete('proiecte',array('id'=>$id));
        if($response)
        {
            return "proiecte deleted successfully";
        }
        else
        {
            return "Error occuring while deleting proiecte";
        }
    }
}
